// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReactWithASP.Server.Data;

#nullable disable

namespace ReactWithASP.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231128170533_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReactWithASP.Server.Models.ConnectionStrings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("dbEncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dbName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dbType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConnectionStrings");
                });

            modelBuilder.Entity("ReactWithASP.Server.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d63f0ca3-e25d-4583-9354-57f110538f45"),
                            Email = "dev@tuckerjohnson.me",
                            FirstName = "Tucker",
                            LastName = "Johnson",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = new Guid("d63f0ca3-e25d-4583-9354-57f110538a55"),
                            Email = "hashtimemail@gmail.com",
                            FirstName = "Tucker",
                            LastName = "Johnson",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ReactWithASP.Server.Models.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserAccount");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d63f0ca3-e25d-4583-9354-57f110538f45"),
                            Email = "dev@tuckerjohnson.me",
                            PasswordHash = "$2a$11$.uLwuTWjCMnTaXborDtiYO25N4EiBGWXiAER6iT9wjGyzJvFtfPSi",
                            RefreshToken = "UdaLvOn1W+GJsTxjQw4auzp+gwb8QCUp8Zmme6FfvMggOkutoLe1GvlKUivBT2aspLzFCGzCEphk9zCmDVaK0g==",
                            TokenCreated = new DateTime(2023, 11, 28, 17, 5, 33, 687, DateTimeKind.Utc).AddTicks(7558),
                            TokenExpires = new DateTime(2023, 11, 28, 17, 35, 33, 687, DateTimeKind.Utc).AddTicks(7551)
                        },
                        new
                        {
                            UserId = new Guid("d63f0ca3-e25d-4583-9354-57f110538a55"),
                            Email = "hashtimemail@gmail.com",
                            PasswordHash = "$2a$11$r8mZQDkgMmVn3/I.oa6mcuZpGuHAvUi7BvrgiV1bIKx750JA0gYGq",
                            RefreshToken = "2wIuenT4Dk6lhMukbEb6iBmd4Y+S2n103SNXuxwzh8EKHfHpNMr6r0UIk2+EHXRUb89c+ON+JfgtF/kN+N7UYQ==",
                            TokenCreated = new DateTime(2023, 11, 28, 17, 5, 33, 787, DateTimeKind.Utc).AddTicks(6475),
                            TokenExpires = new DateTime(2023, 11, 28, 17, 35, 33, 787, DateTimeKind.Utc).AddTicks(6470)
                        });
                });

            modelBuilder.Entity("ReactWithASP.Server.Models.ConnectionStrings", b =>
                {
                    b.HasOne("ReactWithASP.Server.Models.User", "User")
                        .WithMany("ConnectionStrings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactWithASP.Server.Models.User", b =>
                {
                    b.Navigation("ConnectionStrings");
                });
#pragma warning restore 612, 618
        }
    }
}
